import type { ResourceDef } from "./types";

const seoFields = [
  {
    name: "seoTitle",
    label: "SEO title",
    type: "text",
    group: "seo",
    help: "Shown in search results. ≤60 chars ideal, ≤70 max.",
  },
  {
    name: "seoDescription",
    label: "SEO description",
    type: "textarea",
    group: "seo",
    help: "120–155 chars ideal.",
  },
  {
    name: "seoPrimaryKeyword",
    label: "Primary keyword",
    type: "primaryKeyword",
    group: "seo",
    help: "The one focus keyword this page is optimised for.",
    placeholder: "construction company Jaipur",
  },
  {
    name: "seoSecondaryKeywords",
    label: "Secondary keywords",
    type: "secondaryKeywords",
    group: "seo",
    help: "3–5 supporting / LSI variants. Comma-separated.",
  },
  {
    name: "seoOgImage",
    label: "OG / share image",
    type: "image",
    group: "seo",
    recommendedSize: "1200×630px (social share)",
    help: "Used for Facebook, WhatsApp, LinkedIn, Twitter card preview.",
  },
  {
    name: "seoOgTitle",
    label: "OG title",
    type: "text",
    group: "seo",
    help: "Override the share-card title. Defaults to SEO title.",
  },
  {
    name: "seoOgDescription",
    label: "OG description",
    type: "textarea",
    group: "seo",
    help: "Override the share-card description. Defaults to SEO description.",
  },
  {
    name: "seoCanonicalUrl",
    label: "Canonical URL",
    type: "text",
    group: "seo",
    help: "Absolute URL. Leave blank to use the page's own URL.",
    placeholder: "https://…",
  },
  {
    name: "seoNoIndex",
    label: "Hide from search engines",
    type: "boolean",
    group: "seo",
    placeholder: "noindex (page won't appear in Google)",
  },
  {
    name: "seoNoFollow",
    label: "Don't follow links on this page",
    type: "boolean",
    group: "seo",
    placeholder: "nofollow (links won't pass authority)",
  },
] as const;

export const RESOURCES: Record<string, ResourceDef> = {
  projects: {
    key: "projects",
    label: "Projects",
    apiPath: "/projects",
    identifier: "id",
    listColumns: ["title", "market", "year", "location"],
    fields: [
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "market", label: "Market", type: "text", required: true },
      { name: "location", label: "Location", type: "text", required: true },
      { name: "year", label: "Year", type: "number", required: true },
      { name: "client", label: "Client", type: "text" },
      { name: "size", label: "Size", type: "text" },
      { name: "duration", label: "Duration", type: "text" },
      { name: "summary", label: "Summary", type: "richtext", required: true },
      { name: "description", label: "Description", type: "richtext" },
      {
        name: "coverImage",
        label: "Cover image",
        type: "imageWithAlt",
        recommendedSize: "1600×1000px (16:10 landscape)",
      },
      {
        name: "gallery",
        label: "Gallery",
        type: "imageArray",
        recommendedSize: "1400×900px each",
      },
      { name: "highlights", label: "Highlights", type: "stringArray" },
      { name: "sortOrder", label: "Sort order", type: "number", group: "meta" },
      ...seoFields,
    ],
  },
  services: {
    key: "services",
    label: "Services",
    apiPath: "/services",
    identifier: "id",
    listColumns: ["title", "summary"],
    fields: [
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "summary", label: "Summary", type: "richtext", required: true },
      {
        name: "icon",
        label: "Image / icon",
        type: "imageWithAlt",
        recommendedSize: "1600×1000px (16:10)",
      },
      { name: "bullets", label: "Bullets", type: "stringArray" },
      { name: "body", label: "Body", type: "richtext" },
      { name: "sortOrder", label: "Sort order", type: "number", group: "meta" },
      ...seoFields,
    ],
  },
  articles: {
    key: "articles",
    label: "Blog",
    apiPath: "/articles",
    identifier: "id",
    listColumns: ["title", "author", "category", "publishedAt"],
    fields: [
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "excerpt", label: "Excerpt", type: "richtext", required: true },
      { name: "body", label: "Body", type: "richtext" },
      {
        name: "cover",
        label: "Cover image",
        type: "imageWithAlt",
        recommendedSize: "1600×1000px (16:10 landscape)",
      },
      { name: "author", label: "Author", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "publishedAt", label: "Published at", type: "text", help: "ISO date" },
      { name: "sortOrder", label: "Sort order", type: "number", group: "meta" },
      ...seoFields,
    ],
  },
  leaders: {
    key: "leaders",
    label: "Leaders",
    apiPath: "/leaders",
    identifier: "id",
    listColumns: ["name", "role"],
    fields: [
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "role", label: "Role", type: "text", required: true },
      { name: "bio", label: "Bio", type: "richtext" },
      {
        name: "portrait",
        label: "Portrait",
        type: "imageWithAlt",
        recommendedSize: "800×800px (1:1 square)",
      },
      { name: "sortOrder", label: "Sort order", type: "number", group: "meta" },
      ...seoFields,
    ],
  },
  locations: {
    key: "locations",
    label: "Locations",
    apiPath: "/locations",
    identifier: "id",
    listColumns: ["city", "phone", "email"],
    fields: [
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "city", label: "City", type: "text", required: true },
      { name: "address", label: "Address lines", type: "stringArray" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "email", label: "Email", type: "text" },
      {
        name: "image",
        label: "Image",
        type: "imageWithAlt",
        recommendedSize: "1200×800px (3:2 landscape)",
      },
      { name: "sortOrder", label: "Sort order", type: "number", group: "meta" },
    ],
  },
  testimonials: {
    key: "testimonials",
    label: "Testimonials",
    apiPath: "/testimonials",
    identifier: "id",
    listColumns: ["author", "company", "role"],
    fields: [
      { name: "quote", label: "Quote", type: "richtext", required: true },
      { name: "author", label: "Author", type: "text", required: true },
      { name: "role", label: "Role", type: "text" },
      { name: "company", label: "Company", type: "text" },
      {
        name: "avatar",
        label: "Avatar",
        type: "imageWithAlt",
        recommendedSize: "400×400px (1:1 square)",
      },
      { name: "sortOrder", label: "Sort order", type: "number", group: "meta" },
    ],
  },
};

export const RESOURCE_KEYS = Object.keys(RESOURCES);

export function getResource(key: string): ResourceDef | null {
  return RESOURCES[key] ?? null;
}
